DROP TABLE IF EXISTS filhos;
DROP TABLE IF EXISTS documentos;

CREATE TABLE documentos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    rua TEXT NOT NULL
);

CREATE TABLE filhos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    documento_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    FOREIGN KEY (documento_id) REFERENCES documentos(id) ON DELETE CASCADE
);
